# **FINAL PROJECT**

# **1. INTRODUCTION**

Kelompok 3 : 
1. Aan Nurliyanah
2. Ajeng Nilta Adriani
3. Fachmi Maris F.
4. Muhammad Fawwaz Dynoeputra Isnandar
5. Ropiudin

Link Deployment : 

Dataset pada penilitian ini adalah data yang berisi data berdasarkan Kuesioner yang diisi Calon Nasabah untuk mengetahu klasifikasi risk profile calon nasabah sebelum melakukan investasi reksadana. Berdasarkan risk profile dari calon nasabah maka kami akan memberikan rekomendasi produk reksadana mana yang cocok untuk dipilih calon nasabah. Selain memberikan rekomendasi jenis dan produk reksadana, kelompok kami akan memberikan forecasting harga dari reksadana tersebut untuk 4 minggu ke depan.

|      `COLUMN`      | DESCRIPTION                                                                                                       |
| :----------------: | :---------------------------------------------------------------------------------------------------------------- |
|    `Age`    | Informasi tentang umur                                                                                                       |
|      `Expenses`      | Informasi tentang persentase biaya yang dikeluarkan dari income yang didapatkan                                                                        |
|  `Financial Status`   | Informasi tentang komisi perbandingan antara utang dengan asset                                                            |
|     `Experience`      | Informasi tentang pengalaman Nasabah dalam berinvestasi                                                               |
|    `Estimated Period`    | Informasi tentang jangka waktu Nasabah dalam melakukan investasi)                                                              |
|      `Scenario`      | Informasi tentang perbandingan antara mendapatkan keuntungan dan kerugian dalam berinvestasi                                                          |
|   `Unwilling toAccpet`   | Informasi tentang toleransi kerugian yang di harapkan oleh Nasabah)                                                         |
|  `Sum_Scores`   | Klasifikasi profile pada Nasabah                                        |

AGE :    
- Over 55 years (1)
- 45 - 55 years (2)
- 35 - 44 years (3)
- Under 35 Years (4)

EXPENSES :
- LEBIH DARI 75 % dari income (1)
- 50-75 % dari income (2)
- 25-50% dari income (3)
- Dibawah 25% (4)

FINANCIAL STATUS :
- debts > asset (1)
- debts = asset (2)
- debts < asset (3)
- have invest of pension (4)

EXPERIENCE :
- Bank Deposit (1)
- Bonds (Obligasi) (2)
- Fixed Income (Pendapatan Tetap) (3)
- High Rate Asset (4)

ESTIMATED PERIOD :
- Under 1 year (1)
- 1 - 3 year (2)
- 3 - 5 year (3)
- Over 5 year (4)

SCENARIO :
- return 2.5% loss 0% (1)
- return 7% loss 1% (2)
- return 15% loss 5% (3)
- return 25% loss 15% (4)

UNWILLING TO ACCEPT (**TOLERANSI KERUGIAN**):
- Below 5% (1)
- 5-10% (2)
- 10-20% (3)
- Above 20% (4)

SUM SCORES : 
1. "<10"   = Low Risk (**Very Cautious**)
2. "11-15" = Low to moderate Risk (**Cautious**)
3. "16-21" = Moderate to moderately high risk (**Balanced**)
4. "22-26" = High Risk (**Adventurous**)
5. ">26"   = Very High risk (**Speculative**)

# 1.2 Objectives

The objectives in this final project 
1. Classification Customer Ris Profile 
2. Give Recommendation Based on Risk Profile Customer
3. Prediction price high and low forecasting 

# **2. IMPORT LIBRARIES**

Import the library to be used in dataset analysis.

In [1]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OrdinalEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.metrics import accuracy_score, classification_report, ConfusionMatrixDisplay,confusion_matrix
import pickle 
import random

pd.set_option('display.max_column', None)
pd.set_option('display.max_rows',100)
import warnings
warnings.filterwarnings('ignore')

# **3. DATA LOADING** 

Chapter three is intended as a chapter for loading data into a notebook. The data entered into the notebook will be assigned to the df variable. Then, after the data is successfully loaded into the notebook I will show a preview of the first 5 rows in the dataset.

In [2]:
df = pd.read_csv('FinalDataFix.csv')

In [3]:
df.head()

Unnamed: 0  age  expenses  financial_status  experience  estimated_period  \
0           0    2         4                 2           3                 2   
1           1    3         3                 2           4                 3   
2           2    4         3                 4           6                 4   
3           3    3         4                 4           5                 4   
4           4    4         1                 1           2                 2   

   unwilling_toAccept  scenario  sum_scores    salary  
0                   2         4           3  97036796  
1                   4         4           4  84735152  
2                   1         3           4   5201451  
3                   1         1           4  22683827  
4                   4         4           3   3340289

In [4]:
df.head()

Unnamed: 0  age  expenses  financial_status  experience  estimated_period  \
0           0    2         4                 2           3                 2   
1           1    3         3                 2           4                 3   
2           2    4         3                 4           6                 4   
3           3    3         4                 4           5                 4   
4           4    4         1                 1           2                 2   

   unwilling_toAccept  scenario  sum_scores    salary  
0                   2         4           3  97036796  
1                   4         4           4  84735152  
2                   1         3           4   5201451  
3                   1         1           4  22683827  
4                   4         4           3   3340289

## **4. DATA CLEANING AND MANIPULATION**

In [5]:
df.drop(columns='Unnamed: 0',inplace=True)

Menghapus kolom Unnamed: 0 karena tidak diperlukan dalam penilitian project ini. 

In [6]:
df.duplicated().any()

False

Dalam dataset ini tidak ditemukannya data duplicated.

## **5. DATA SPLITTING**

In [7]:
#Splitting inference data
inference = df.sample(2)
inference

age  expenses  financial_status  experience  estimated_period  \
8406    4         4                 4           5                 4   
7202    3         4                 1           8                 2   

      unwilling_toAccept  scenario  sum_scores    salary  
8406                   4         4           5  14076211  
7202                   3         3           4  20305432

Dapat kita ketahui dataframe diatas untuk menampilkan satu data inference yang diambil.

In [8]:
#Dropping inferenced data
df = df.drop(inference.index, axis = 0)

In [9]:
X = df.drop('sum_scores',axis=1)
y = df['sum_scores']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [10]:
print(f'X_train shape : ',X_train.shape)
print(f'X_test shape : ',X_test.shape)
print(f'y_train shape : ',y_train.shape)
print(f'y_test shape : ',y_test.shape)

X_train shape :  (7498, 8)
X_test shape :  (2500, 8)
y_train shape :  (7498,)
y_test shape :  (2500,)


Proses pembagian data kedalam 3 dataframe, yaitu: 
- data train dengan besaran 75% dari data 
- data test dengan besaran 25% dari data 

Penentuan kolom target dan kolom feature yang dituliskan dengan y untuk target dan x untuk feature

## **PREPROCESSING PIPELINE**

In [11]:
#Scaling on salary column
num_pipeline = Pipeline([
    ('scaler', StandardScaler())])

num_tr = num_pipeline.fit_transform(X_train[['salary']])

Membuat fungsi pipeline untuk melakukan proses scaling untuk kolom salary.

In [12]:
#Creating a column transformer to transform salary columns
full_pipeline = ColumnTransformer([
        # ("cat", cat_pipeline, ['age','expenses','financial_status','experience','estimated_period','unwilling_toAccept','scenario']),
        ("num", num_pipeline, ['salary'])
    ], remainder='passthrough')

train_tr = full_pipeline.fit_transform(X_train)
train_tr

array([[-1.01191956,  1.        ,  1.        , ...,  1.        ,
         1.        ,  1.        ],
       [-0.28028641,  2.        ,  4.        , ...,  4.        ,
         3.        ,  3.        ],
       [ 1.64699015,  1.        ,  3.        , ...,  2.        ,
         3.        ,  3.        ],
       ...,
       [ 1.32954285,  1.        ,  1.        , ...,  4.        ,
         2.        ,  3.        ],
       [ 0.21002971,  4.        ,  3.        , ...,  1.        ,
         4.        ,  3.        ],
       [ 1.57403839,  1.        ,  1.        , ...,  1.        ,
         1.        ,  2.        ]])

In [13]:
test_tr = full_pipeline.transform(X_test)
test_tr

array([[ 0.55322842,  2.        ,  3.        , ...,  4.        ,
         1.        ,  2.        ],
       [ 0.2531943 ,  3.        ,  4.        , ...,  4.        ,
         1.        ,  1.        ],
       [-1.67932916,  3.        ,  1.        , ...,  4.        ,
         1.        ,  3.        ],
       ...,
       [ 0.50615414,  2.        ,  2.        , ...,  1.        ,
         4.        ,  2.        ],
       [-0.11124835,  1.        ,  1.        , ...,  1.        ,
         1.        ,  1.        ],
       [ 1.39165595,  1.        ,  2.        , ...,  2.        ,
         1.        ,  2.        ]])

## **FULL PIPELINE**

## 8.1 Model Definition

Pada bagian ini saya membuat model pembelajaran Machine Learning.

In [14]:
#Initiating SVC Model
svc = SVC()

In [15]:
#Initiating all process pipeline
all_process = Pipeline([
    ("preprocessing", full_pipeline),
    ("svc", svc )
])

In [16]:
all_process.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  ['salary'])])),
                ('svc', SVC())])

In [17]:
train_result = all_process.predict(X_train)
test_result = all_process.predict(X_test)

In [18]:
print("=="*20,"TRAINING","=="*20)
print(classification_report(y_train,train_result,zero_division=0))
print("=="*20,"TEST","=="*20)
print(classification_report(y_test,test_result,zero_division=0))

======================================== TRAINING ========================================
              precision    recall  f1-score   support

           1       1.00      0.99      1.00       911
           2       0.99      1.00      0.99       770
           3       1.00      1.00      1.00      3412
           4       0.98      1.00      0.99      1661
           5       1.00      0.95      0.97       744

    accuracy                           0.99      7498
   macro avg       0.99      0.99      0.99      7498
weighted avg       0.99      0.99      0.99      7498

======================================== TEST ========================================
              precision    recall  f1-score   support

           1       1.00      0.99      0.99       308
           2       0.98      0.99      0.99       245
           3       1.00      1.00      1.00      1153
           4       0.97      1.00      0.98       546
           5       1.00      0.94      0.97       248

    acc

Berdasarkan performansi model SVM dilakukan, dapat diinterpretasi sebagai berikut:

1. Pada Model SVM menggunakan parameter baseline memiliki model yang bestfit, dikarnakan performa test memiliki selisih yang tidak terlalu besar dengan performa train.
2. Dan model SVM memiliki nilai recall pada data testing yaitu sebesar 99% yang berarti kesalahan negatifnya tidak terlalu besar. Sehingga dapat disimpulkan model sudah dikategorikan baik

## **INFERENCE**

In [19]:
inference = inference[['salary','age','expenses','financial_status','experience','estimated_period','unwilling_toAccept','scenario']]

Predict model inference menggunakan pipeline

In [20]:
# full_pipeline.transform(inference)
all_process.predict(inference)

array([5, 4], dtype=int64)

save pipeline model inference

In [21]:
# save pipeline
pickle.dump(full_pipeline, open("full_model.pkl", "wb"))
# save model
pickle.dump(svc, open('model.pkl', 'wb'))

#### **TESTING THE SAVED MODEL**

In [22]:
model = pickle.load(open("full_model.pkl", "rb"))

In [23]:
inf = inference.head(1)
inf

salary  age  expenses  financial_status  experience  estimated_period  \
8406  14076211    4         4                 4           5                 4   

      unwilling_toAccept  scenario  
8406                   4         4

In [27]:
# pipeline model predict input data
Category = all_process.predict(inf).tolist()[0]
Category

5

# **10. CONCLUSION**

Dari Overall analysis dapat disimpulkan bahwa : 
1. Pada final project ini dilakukan pembuatan model machine learning Supervised Classification untuk mengetahui risk profile customer yang terdiri dari 10.000 entri data dan 8 kolom.
2. Dilakukan pembuatan pipeline pada proses preprocessing dan modeling
3. Risk Profile Customer ditentukan dari kuesioner nasabah yang akan melakukan investasi reksa dana.
4. Rekomendasi klasifikasi Reksa Dana berdasarkan Risk Profile yaitu : 
   ```
   a. Low Risk (Very Cautious)
   b. Low to moderate Risk (Cautious)
   c. Moderate to moderately high risk (Balanced)
   d. High Risk (Adventurous)
   e. Very High risk (Speculative)
   ```
5. Model Machine Learning yang digunakan yaitu Model SVM
6. Berdasarkan hasil diperoleh model terbaik yaitu model SVM dengan nilai accuracy 99%
